# Generated by Django 4.2 on 2023-07-27 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_alter_recepies_recepie_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recepies',
            name='recepie_image',
            field=models.ImageField(upload_to='recipe_images'),
        ),
    ]
