# Generated by Django 4.2.3 on 2023-07-30 05:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_recipe_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='recepie_view_count',
            field=models.IntegerField(default=1),
        ),
    ]
