# Generated by Django 4.2.3 on 2023-07-30 06:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_recipe_recepie_view_count'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='recepie_view_count',
            field=models.IntegerField(),
        ),
    ]
