# Generated by Django 4.2.3 on 2023-08-02 16:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_department_studentid_student'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recipe',
            name='recepie_view_count',
        ),
    ]
